config/routes.rb
Rails.application.routes.draw do
root 'notes#index'
resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all
  end

  def new
  @note = Note.new
  end

  def create
    Note.create(note_params)
    redirect_to root_path
  end

private

  def note_params
    params.require(:note).permit(:name, :date, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<h1 class= "text-center">Keeping Personal Notes organized and Ready for Review! </h1>
<div class="container text-center">
<%= link_to 'Write a Note', new_note_path %>
</div>
<% @notes.each do |note| %>
  <div class="booyah-boz col-10 offset-1">
    <h1><%= note.name %></h1><br />
    <i><%= note.date %></i><br />
    <p><%= note.description %></p><br />
  </div>

  <hr />
<% end %>

app/views/notes/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Gotta Write Notes!</h1>
  <%= simple_form_for @note do |f| %>
    <%= f.input :name %>
    <%= f.input :date %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Post Note', class: 'btn btn-primary' %>
  <% end %>
</div>